FROM openjdk:slim
COPY --from=python:3.9 / /

WORKDIR /service

COPY requirements.txt /service/requirements.txt

RUN python -m pip install --upgrade pip
RUN pip install -r /service/requirements.txt
RUN apt-get update

EXPOSE 80

ADD . /src

WORKDIR /src

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"] 
